# 输出日志
logging:
  level:
    com.example.sky.mapper: debug

# tomcat 服务器
server:
  port: 8080

# spring 框架
spring:
  application:
    name: sky
  # mysql 数据库
  datasource:
    druid:
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sky
  # redis 数据库
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 0

# mybatis 框架
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sky.pojo.entity
  configuration:
    # 下划线 -> 驼峰映射
    map-underscore-to-camel-case: true

sky:
  # jwt 认证
  jwt:
    admin-secret-key: eyrg47q397827yh847q9378ryg3whjxq8394qy283947y23rybwnvejmcwdgrw3iqhmoi3yrfgqhdw
    admin-timeout: 7200000
    admin-token-name: token
    user-secret-key: egwwiqeouvw4icqi4ryq3xw9ocirhcweuddfveiildkcweb7rixcwievrgcwjakesvyfhseoivbtgjqo
    user-timeout: 7200000
    user-token-name: authentication


